service: recreahub

provider:
  name: aws
  httpApi:
    cors: true
    authorizers:
      customAuthorizer:
        type: request
        functionName: authorizerFunc
        payloadVersion: '2.0
        enableSimpleResponses: true


functions:
  authorizerFunc:
    handler: index.authorizer
    
  CreateLotFn:
    handler: index.CreateLotFn
    events:
      - httpApi:
        method: POST
        path: /lots

  ListLotsFn:
    handler: index.ListLotsFn
    events:
      - httpApi:
        method: GET
        path: /lots
  
  ReserveLotFn:
    handler: index.ReserveLotFn
    vents:
      - httpApi:
        method: UPDATE
        path: /lots/{lotId}/reserve
